version: "3.8"

services:
  portainer:
    ports:
      - "9000:9000"

  mariadb:
    ports:
      - "3306:3306"

  phpmyadmin:
    ports:
      - "9090:80"
      
  redis:
    ports:
      - "6379:6379"
  
  rabbitmq:
    ports:
      - "5672:5672"
      - "15672:15672"

  traefik:  
    ports:
      - "80:80"
      - "8080:8080"

  rabbitmq1:
    ports:
      - "8081:15672"

  rabbitmq2:
    ports:
      - "8082:15672"
